version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: cloud-tasks-emulator
    main: ./cmd/server
    binary: cloud-tasks-emulator
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

dockers:
  - dockerfile: Dockerfile.release
    image_templates:
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}
      - ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest
    use: buildx
    goos: linux
    goarch: amd64

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
